language: python
python:
  - "2.7_with_system_site_packages"
  - "3.4_with_system_site_packages"
before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy python-cython python-matplotlib
install:
  - pip install -r requirements.txt
  - pip install pep8
script:
  - pep8 .
  - python test.py
