package:
  name: neurodynex
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - mock
    - nose
    - numpy
    - scipy
    - brian2 >=2.0b4
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - brian2 >=2.0b4
    - matplotlib
    - ipython

test:
  # Python imports
  imports:
    - neurodynex
    - neurodynex.leaky_integrate_and_fire
    - neurodynex.hodgkin_huxley
    - neurodynex.hopfield_network
    - neurodynex.neuron_type
    - neurodynex.phase_plane_analysis
    - neurodynex.test

  commands:
    - nosetests neurodynex.test.test_LIF
    - nosetests neurodynex.test.test_HH
    - nosetests neurodynex.test.test_hopfield
    - nosetests neurodynex.test.test_nagumo
    - nosetests neurodynex.test.test_neuron_type

  requires:
    - nose

about:
  home: https://github.com/EPFL-LCN/neuronaldynamics-exercises
  license: GNU General Public License v2 (GPLv2)
  summary: 'Python exercises accompanying the book Neuronal Dynamics by Wulfram Gerstner, Werner M. Kistler, Richard Naud and Liam Paninski.'